# Site settings
title: Paul R Johnston
email: paul.johnston@fu-berlin.de
url: https://example.github.io
description: "Postdoc, Rolff Lab/Berlin Centre for Genomics in Biodiversity"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Paul R Johnston

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Paul_R_Johnston
  - title: github
    url: https://github.com/Perugolate

# Build settings
markdown: kramdown
permalink: pretty
